### ISSUE TITLE
Schedule#add doesn't use "args"

### ISSUE THREAD

**Issue by njam** [cargomedia/copperegg-alerts#9]
I think, can you double check @ppp0 ?

**Comment by ppp0** [comment]
@njam sorry I unsuccessfully tried to make a sense out of this..

in https://github.com/cargomedia/copperegg-alerts/blob/master/spec/alert_spec.rb#L29 and https://github.com/cargomedia/copperegg-alerts/blob/master/spec/alert_spec.rb#L38 is where `Copperegg::Alerts::Schedule#add` is being used.

afaics the args are passed in a POST request to the API?

How did you come across this bug?

**Comment by ppp0** [comment]
May be this one: https://github.com/cargomedia/pulsar-conf-cargomedia/blob/89e3b6749fe3ae6d99de59d062ba50bb267970bd/recipes/generic/copperegg.rb#L40 should be a list of hashes, not a hash?

**Comment by njam** [comment]
Agree, looks fine.
I think I was just confused that we're using `defaults` to send the request (and args get merged into the defaults)?

**Comment by ppp0** [comment]
good to hear
